### PR TITLE
Fixed: Handle images that aren't found a bit more gracefully.

### LINKED ISSUE #7080: `{{ image('foo.bar') }}` gives an error, should not do that.
For example: 

```
{{ image('foo.bar', 100, 100) }}
```

Outputs: `thumbs/100x100c/foo.bar`

```
{{ image('') }}
```

outputs nothing. 

Currently `{{ image('foo.bar') }}` gives an error like below. It should do either of the above two. 

screen shot 2017-10-13 at 16 08 59

### PR DESCRIPTION
**Pull request by bobdenotter**
Fixes #7080.

Before, if debug was disabled, it would just show the "whoops something went wrong", which is not very user friendly. Now it falls back to the pleasant 404 image, while maintaining the exception for when you're in development (debug) mode.

### CODE REVIEW

File: src/Twig/Runtime/ImageRuntime.php [hunk 1]
```diff
@@ -74,13 +75,22 @@ public function image($fileName = null, $width = null, $height = null, $crop = n
...
-        $file = $this->filesystemMatcher->getFile($fileName);
-
-        $url = $file->url();
+        try {
+            $file = $this->filesystemMatcher->getFile($fileName);
+            $url = $file->url();
+        } catch (FileNotFoundException $e) {
+            // If a non-existing filename is given, we either re-throw the Exception (in DEV) or defer to the
+            // Thumbnailer, so the user sees the "404 image".
+            if ($this->config->get('general/debug')) {
```
Comment (CarsonF) [inline src/Twig/Runtime/ImageRuntime.php]: It would be better to use `$twigEnv->isDebug()` instead here.

Comment (GawainLynch) [reply src/Twig/Runtime/ImageRuntime.php]: See #7122
