### PR TITLE
Fixes for {{ dump() }}

### LINKED ISSUE #5122: [2.2] templates output `{{ dump() }}` when not logged in.
See screenshot: 

screen shot 2016-04-05 at 13 42 06

### PR DESCRIPTION
**Pull request by bobdenotter**
- Don’t show dump when user not logged on.
- Honor `debug_show_loggedoff` setting
- Apply the same for `firebug` and `backtrace`. Not just `dump`.

Fixes #5122

### CODE REVIEW

**Comment by GawainLynch** [comment]
Can thou adjust tests for this one, or woultst thou liketh helpeth?

**Comment by bobdenotter** [comment]
Was just looking into that..

```
1) Bolt\Tests\Twig\BoltTwigHelpersTest::testPrintDump
null does not match expected type "array".

2) Bolt\Tests\Twig\BoltTwigHelpersTest::testPrintBacktrace
Failed asserting that a NULL is not empty.
```

I think we'd need to set `debug_allow_loggedoff` on the fly, right?

**Comment by GawainLynch** [comment]
This fixes it for me…

```php
diff --git a/tests/phpunit/unit/Twig/BoltTwigHelpersTest.php b/tests/phpunit/unit/Twig/BoltTwigHelpersTest.php
index aebb19b..08fb342 100644
--- a/tests/phpunit/unit/Twig/BoltTwigHelpersTest.php
+++ b/tests/phpunit/unit/Twig/BoltTwigHelpersTest.php
@@ -65,6 +65,7 @@ class BoltTwigHelpersTest extends BoltUnitTest
 
         // Now test with debug enabled
         $app = $this->getApp();
+        $app['config']->set('general/debug_show_loggedoff', true);
         $handlers = $this->getTwigHandlers($app);
         $twig = new TwigExtension($app, $handlers, false);
         $this->assertEquals($list, $twig->printDump($list));
@@ -89,6 +90,7 @@ class BoltTwigHelpersTest extends BoltUnitTest
 
         // Debug mode
         $app = $this->getApp();
+        $app['config']->set('general/debug_show_loggedoff', true);
         $handlers = $this->getTwigHandlers($app);
         $twig = new TwigExtension($app, $handlers, false);
         $this->assertNotEmpty($twig->printBacktrace());
```

File: src/Twig/Handler/UtilsHandler.php [hunk 1]
```diff
@@ -170,4 +167,23 @@ public function request($parameter, $from, $stripslashes, $safe)
...
+     *
+     * @return boolean
+     */
+    private function allowDebug($safe)
+    {
+        return (
+            !$safe &&
+            ( ($this->app['debug'] && $this->app['users']->getCurrentUser()) ||
+            $this->app['config']->get('general/debug_show_loggedoff') ) );
+    }
```
Comment (CarsonF) [inline src/Twig/Handler/UtilsHandler.php]: Shouldn't `debug` control whether it's shown?

```
$this->app['debug'] && ($this->app['users']->getCurrentUser()) || $this->app['config']->get('general/debug_show_loggedoff'))
```

**Comment by GawainLynch** [comment]
Fail on this is due to #5701 and fixed in #5135
