### PR TITLE
Only use `news_variable` from `config.yml`, if it's actually present in the news feed.

### LINKED ISSUE #7229: [3.4] backend breaks on 'dashboardnews' if people are not paying attention very well to what they're doing.
If you're not paying attention, it's pretty easy to break the bolt backend. 

To reproduce: 

1) Set up a default Bolt instance, using your preferred method. 

2) Think to yourself "I'd like to set the branding options!"

3) Edit config.yml, and uncomment the following section from the default configuration: 

```yaml
branding:
    name: SuperCMS
    path: /admin
    provided_by: [ supercool@example.org, "Supercool Webdesign Co." ]
    news_source: http://news.bolt.cm
    news_variable: news
```

4) Visit the bolt backend: 

screen shot 2017-12-03 at 17 28 59

### PR DESCRIPTION
**Pull request by bobdenotter**
Fixes #7229.

Note: I'm using `json_decode($fetchedNewsData, true)` because it seems that it's dependant on the format of the feed whether or it's an object or an array. Using `true` makes sure we get an array, and the check for `$newsVariable` doesn't break.

### CODE REVIEW

File: src/Controller/Async/General.php [hunk 1]
```diff
@@ -393,9 +393,11 @@ private function fetchNews($hostname)
             ];
         }
 
-        $fetchedNewsItems = json_decode($fetchedNewsData);
-        if ($newsVariable = $this->getOption('general/branding/news_variable')) {
-            $fetchedNewsItems = $fetchedNewsItems->$newsVariable;
+        $fetchedNewsItems = json_decode($fetchedNewsData, true);
```
Comment (GawainLynch) [inline src/Controller/Async/General.php]: Oh dear … it seems I missed this one in the `bolt/common` cutover … or I derped a merge :disappointed: 

`$fetchedNewsItems = \Bolt\Common\Json::parse($fetchedNewsData)` will do the same job, plus it will throw a catchable exception if there is _any_ problem in the decoding … at which point (the catch) you can return something friendly to the end user.

Comment (bobdenotter) [reply src/Controller/Async/General.php]: Ah, derp! I knew that.. 

I'll work on this PR some more.

Comment (GawainLynch) [reply src/Controller/Async/General.php]: Oh, it is totally not your fault here … mine if anyone's.

Comment (bobdenotter) [reply src/Controller/Async/General.php]: Regardless, it's a good pointer to improve the current PR, so i'll work on it. ;-)

**Comment by bobdenotter** [comment]
Updated.
