### PR TITLE
Fix domain cookie value with http port

### LINKED ISSUE #5114: [BUG] Default cookie domain value in header can't contain port number
In case of server addressed via any port number like http://bolt.me:8080 and no explicit _cookies_domain_ value set to _.bolt.me_ then right session storage can't be reached by the app.
This will be producing CSRF errors at first user creation like mentioned in #5014.

Details
-------

 - Bolt Version: [ master ]

Screenshot:
Response header

### PR DESCRIPTION
**Pull request by rixbeck**
Default cookie domain value can't contain server's http port number.
Resolves partially #5014 and resolves #5114

### CODE REVIEW

**Comment by bobdenotter** [comment]
For me (locally) this breaks in entirely different ways: 

screen shot 2016-04-05 at 12 20 08

File: src/Config.php [hunk 1]
```diff
@@ -325,10 +325,10 @@ protected function parseGeneral()
...
-            if (isset($_SERVER['HTTP_HOST'])) {
-                $hostname = $_SERVER['HTTP_HOST'];
-            } elseif (isset($_SERVER['SERVER_NAME'])) {
+            if (isset($_SERVER['SERVER_NAME'])) {
                 $hostname = $_SERVER['SERVER_NAME'];
+            } elseif (isset($_SERVER['HTTP_HOST'])) {
+                $hostname = reset(explode(':', $_SERVER['HTTP_HOST']));
             } else {
                 $hostname = '';
             }
```
Comment (GawainLynch) [inline src/Config.php]: Might want to go for something like:
```php
            $request = Request::createFromGlobals();
            if ($request->server->get('HTTP_HOST', false)) {
                $hostHeaders = explode(':', $request->server->get('HTTP_HOST'));
                $hostname = reset($hostHeaders);
            } elseif ($request->server->get('SERVER_NAME', false)) {
                $hostname = $request->server->get('SERVER_NAME');
            } else {
                $hostname = '';
            }
```

**Comment by bobdenotter** [comment]
Looks good to me!
