### PR TITLE
Set preserve_keys in array_slice to keep numeric array key association

### LINKED ISSUE #7411: [bug] Incorrect saving of select field
Steps
---
(44 sec video - below)
- i have a contenttype field called "works". Here's how it's set up:
    ```yml
    works:
    type: select
    multiple: true
    values: 
        '1'  : 'Motorhomes upholstery'
        '2'  : 'Caravans upholstery'
        '3'  : 'RV upholstery'
        '4'  : 'Camper van upholstery'
        '5'  : 'Static Caravans upholstery'
        '6'  : 'Furniture reupholstery'
    ```
- in content edit i select 2nd and 4th options, press save
- what gets to database? **`["1","3"]`**. Whaa? Ookay, we assume that we're saving array indices of my options, but in _string format_. Okay, looks like we always save strings array. Not asking, why we ignore original keys.
- delete record in DB (field is not required, so it's ok)
- reload content edit in browser
- Now we select 1st and 4th options. Press save
- What comes to db? **`{"1":"3"}`** . Whaaaa💥 Is it an object with a _`key`_ of my first selected option and _`"index"`_ of the second one?

Video
---

## Upd1: What is sent in request ✈️ 

In request plain order indices are sent. So if you select options: 1st and 4th, you'll see in request form data:
**works[]** 0
**works[]** 3

## Upd2: Where the problem is 💩 

• Here's that little naughty piece of  code, that magically converts `["0","3"] to ["1"=>"3"]`:
https://github.com/bolt/bolt/blob/3.4/src/Storage/Entity/Content.php#L60
image

• so, if you don't pass a callback, all *falsy* values will be rejected
```php
$arr = [0, 1, 2, '0', '', null];
print_r(array_filter($arr));  // Will output: Array ( [1] => 1, [2] => 2 )
```

• then, if frontend sends `[0, 3]` in form, only `[1 => 3]` passes.

• And after all it's dumped as `{"1":"3"}` to database.

Resume
---
1. **Array_filter** is a weak part. It rejects 0 option.
2. Frontend sends incorrect keys. So it's a big bug, because if you rely on documentation ([defining-values-as-a-hash](https://docs.bolt.cm/3.4/fields/select#defining-values-as-a-hash)) people will assume that hash `{1: 'option1', 'anotheroption': 'option2'}` will work. But in fact - it won't.

##### Another reproduction:
- create a select key with values: 
```yml
values:
    1: opt1
    2 : opt2
    foo: opt3
```
- create a record, save it
- change the order (1 ←→ 2).
- 💥 you'll get another values.

### PR DESCRIPTION
**Pull request by Boorj**
#### Fixes #7411 
In `Form\Resolve\Choice.php` `array_slice` clears indices of original associative array.

### CODE REVIEW

File: src/Form/Resolver/Choice.php [hunk 1]
```diff
@@ -105,7 +105,19 @@ private function getValues(array $field)
      */
     private function getYamlValues(Bag $field)
     {
-        $values = array_slice($field->get('values', []), 0, $field->get('limit'));
```
Comment (GwendolenLynch) [inline src/Form/Resolver/Choice.php:108]: You just need to add `true` as the 4th parameter to `array_slice()` to do natively what you're recreating below :wink: 

```
$values = array_slice($field->get('values', []), 0, $field->get('limit'), true);
```

**Review by GwendolenLynch — CHANGES_REQUESTED** [review]

File: src/Form/Resolver/Choice.php (hunk 1 above)
Comment (Boorj) [reply src/Form/Resolver/Choice.php:108]: yay! 😀 
(actually, in such situations i dislike all those complex polymorphic functions)

**Comment by Boorj** [comment]
@GawainLynch thank you for help. And for test.

**Review by GwendolenLynch — APPROVED** [review]
