### PR TITLE
Fixes and improvements for Logger test suite

### LINKED ISSUE #2799: LogTest needs to be dealt with. Currently they are skipped.

### PR DESCRIPTION
**Pull request by rossriley**
Fixes #2799

### CODE REVIEW

File: src/Logger/ChangeLogItem.php [hunk 1]
```diff
@@ -152,19 +154,14 @@ private function getEffectiveMutationType()
...
                 continue;
             }
-
-            if ($this->fields[$key]['type'] == 'text' ||
-                $this->fields[$key]['type'] == 'text' ||
-                $this->fields[$key]['type'] == 'text' ||
-                $this->fields[$key]['type'] == 'text' ||
-                $this->fields[$key]['type'] == 'text') {
-                    //
-            }
```
Comment (GawainLynch) [inline src/Logger/ChangeLogItem.php]: Whoopsie :see_no_evil:

**Comment by GawainLynch** [comment]
Thank you! :+1:
