### PR TITLE
New storage layer fixed pagination handling

### LINKED ISSUE #6999: [3.4] Pagination is missing on overview pages in backend.

### PR DESCRIPTION
**Pull request by rossriley**
Fixes #6999 

This finishes off support for pagination, the original query is now exposed via the QueryResultset object and that allows other areas of the codebase to get the query and modify/re-run which will likely be useful in other areas of the code or extensions too.

Also added a dependency injection of the pager manager to the backend content listing action so it can update the pager values accordingly.

### CODE REVIEW

File: src/Storage/ContentRequest/Listing.php [hunk 1]
```diff
@@ -20,19 +22,23 @@ class Listing
...
      *
      * @param EntityManager $em
-     * @param Query         $query
-     * @param Config        $config
+     * @param Query $query
+     * @param Config $config
+     * @param PagerManager $pager
      */
-    public function __construct(EntityManager $em, Query $query, Config $config)
+    public function __construct(EntityManager $em, Query $query, Config $config, PagerManager $pager)
```
Comment (GawainLynch) [inline src/Storage/ContentRequest/Listing.php]: For v3 we'd need to make this `PagerManager $pager = null` to cover BC (and note as such). I had intended on re-doing all this for 3.0.0 but :zipper_mouth_face:

**Comment by GawainLynch** [comment]
I've created a bunch of records (> 10) and set a `recordsperpage: 5` and am not getting the pager back, am I derping?

**Comment by bobdenotter** [comment]
With these latest changes, it seems to be working fine for me: 

screen shot 2017-09-22 at 08 09 02

**Comment by GawainLynch** [comment]
image
image
