### PR TITLE
Fix alt and title tags for popup & showimage, height/width for showImage

### LINKED ISSUE #2866: image ALT attributes
Currently if you use  
```html
{{ record.image|popup(100, 100, "r") }}  
<!-- markup below -->
<a href="/bolt/thumbs/1000x750r/filename.jpg" class="magnific" title="Image: filename.jpg">
  <img src="/bolt/thumbs/100x100r/filename.jpg" width="100" height="100">  
</a>
```
 or 
```html
{{ record.image|showimage(800, 600) }}   

<img src="/bolt/thumbs/800x600c/filename.jpg" width="800" height="600">
```  
There are no alt attributes present. We need these for accessibility purposes and a less significant need of being a valid image tag.  

Most instances a file name can be used without the .jpg/png/gif extentions (if the file name actually describes the image ie. alt="bolt logo") but that isn't very descriptive and in some cases not valid alt attribute text. There is also no place to add a description for the image. Only an option to rename the image.   

I understand this gets into the murky waters of media management and there are no quick fixes ( besides possibly adding a description field to the image in the database).  

more info on alt attributes for anyone interested:  
[web aim atl text](http://webaim.org/techniques/alttext/)
[w3 accessibilty](http://www.w3.org/standards/webdesign/accessibility)

### LINKED ISSUE #4022: twig popup() while $filename is an array
twig imagehandler popup expects a string,
however docs suggest to serve it an image field (array) ``{{ image|popup(200,200,'c') }}``

The imagehandler does pass the filename (array) to its thumbnail method
https://github.com/bolt/bolt/blob/release/2.2/src/Twig/Handler/ImageHandler.php#L183

The thumbnail method extracts the name if it is an array
https://github.com/bolt/bolt/blob/release/2.2/src/Twig/Handler/ImageHandler.php#L298

And then back in popup method, it tries to use filename (still array) for title
https://github.com/bolt/bolt/blob/release/2.2/src/Twig/Handler/ImageHandler.php#L187

### PR DESCRIPTION
**Pull request by SahAssar**
Fixes #4022 and #2275.

All credit for for the title fix to @GDmac which I grabbed from #4022 since I got impatient after waiting for a month ;)

This also seems to fix #2866 if I am not wrong...

### CODE REVIEW

File: src/Twig/Handler/ImageHandler.php [hunk 1]
```diff
@@ -184,16 +184,34 @@ public function popup($filename = '', $width = 100, $height = 100, $crop = '', $
...
+                    } else {
+                        // fallback to filename as provided (string)
+                        $title = sprintf('%s: %s', Trans::__('Image'), $filename);
+                    }
+                }
+            }
+            
+            if (is_array($filename) && isset($filename['alt'])) {
+                $alt = $filename['alt'];
+            }else {
```
Comment (GawainLynch) [inline src/Twig/Handler/ImageHandler.php]: Should be:
```php
} else {
```

File: src/Twig/Handler/ImageHandler.php [hunk 2]
```diff
@@ -226,7 +244,17 @@ public function showImage($filename = '', $width = 0, $height = 0, $crop = '')
             $width = intval($width);
             $height = intval($height);
 
+            if (isset($filename['alt'])) {
+                $alt = $filename['alt'];
+            }elseif (isset($filename['title'])) {
```
Comment (GawainLynch) [inline src/Twig/Handler/ImageHandler.php]: Should be:
```php
} elseif (isset($filename['title'])) {
```

**Comment by bobdenotter** [comment]
Looks good to me!
